//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsMaster.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cooperator
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string Description { get; set; }
        public System.DateTime Created { get; set; }
        public bool IsBanner { get; set; }
        public string UrlAddress { get; set; }
        public string Address { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
    }
}
