//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsMaster.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class News
    {
        public int Id { get; set; }
        [Display(Name="Tytu³")]
        public string Title { get; set; }
        [Display(Name = "Zawartoœæ")]
        public string Content { get; set; }
        [Display(Name = "Utworzono")]
        public System.DateTime Created { get; set; }
    }
}
