//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CmsMaster.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    
    public partial class News
    {
        public int Id { get; set; }

        [Display(Name = "Tytu³")]
        [StringLength(100, ErrorMessage = "Maksymalna d³ugoœæ pola to 100 znaków")]
        public string Title { get; set; }

        [Display(Name = "Zawartoœæ")]
        [UIHint("tinymce_full_compressed"), AllowHtml]
        public string Content { get; set; }

        [Display(Name = "Data utworzenia")]
        public System.DateTime Created { get; set; }
    }
}
